# Generated by Django 6.0.2 on 2026-02-28 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podtasks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="podcast",
            name="title",
        ),
    ]
