# Generated by Django 4.2.30 on 2026-04-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=20)),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['asset', 'timestamp'], name='prices_tick_asset_c0a31d_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('sma_20', models.FloatField(null=True)),
                ('sma_50', models.FloatField(null=True)),
                ('rsi_14', models.FloatField(null=True)),
                ('vwap', models.FloatField(null=True)),
                ('volatility', models.FloatField(null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['asset', 'timestamp'], name='prices_anal_asset_c995df_idx')],
            },
        ),
    ]
