
services:
  python-api-server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: python-api-server
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: shortify
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "4000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - python-api-server

volumes:
  mongo_data:
  redis_data:
